// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtz4DGY-_qrVXyss6BQVhTqyMSwQF0tvo',
    appId: '1:486990515621:web:698a726eabbc66210bec4c',
    messagingSenderId: '486990515621',
    projectId: 'e-commerce-app-e57b8',
    authDomain: 'e-commerce-app-e57b8.firebaseapp.com',
    storageBucket: 'e-commerce-app-e57b8.appspot.com',
    measurementId: 'G-8QL15676Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd6h5IEpMrKZ5HkApaM28op79JxP0pUYA',
    appId: '1:486990515621:android:a22445b0972467790bec4c',
    messagingSenderId: '486990515621',
    projectId: 'e-commerce-app-e57b8',
    storageBucket: 'e-commerce-app-e57b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfRo8GGuRA4Tu-goCONS2QoUY-xCkDd-Y',
    appId: '1:486990515621:ios:ce49127735ef66700bec4c',
    messagingSenderId: '486990515621',
    projectId: 'e-commerce-app-e57b8',
    storageBucket: 'e-commerce-app-e57b8.appspot.com',
    androidClientId: '486990515621-cr592lqvkmpan1eu6b3lqtp9dvjqbisk.apps.googleusercontent.com',
    iosClientId: '486990515621-e4lthppp6rh3270nqqihomth1qtju1t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
